const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let token=sessionStorage.getItem('fe_token')||'', userEmail=sessionStorage.getItem('fe_email')||'', lastAnalysis=null;
function todayISO(){return new Date().toISOString().slice(0,10)}
function pct(v){return v==null?'—':(Number(v)*100).toFixed(1)+'%'}
function num(v,d=2){return v==null?'—':Number(v).toFixed(d)}
function euro(v){return v==null?'—':'€'+Number(v).toFixed(2)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const titles={dashboard:'Dashboard',games:'Jogos',analyzer:'Match Analyzer',value:'Value Finder',backtest:'Backtesting',history:'Histórico',model:'Modelo & Metodologia',account:'Conta'};
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#pageTitle').textContent=titles[id]||id;window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
async function api(url,opts={}){opts.headers=opts.headers||{};if(token)opts.headers.Authorization='Bearer '+token;const r=await fetch(url,opts);let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||'Erro no servidor');return data}
async function health(){try{let d=await api('/api/health');$('#providerName').textContent=d.provider.replace('Provider','')+' · v'+d.version}catch{$('#providerName').textContent='Indisponível'}}
function gameCard(g){const t=new Date(g.kickoff),time=t.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'});return `<article class="game-card" data-home="${esc(g.home)}" data-away="${esc(g.away)}"><div class="game-meta"><span>${esc(g.league||'Competição')}</span><span>${time}</span></div><div class="teams"><div class="team-line"><span>${esc(g.home)}</span><span>CASA</span></div><div class="team-line"><span>${esc(g.away)}</span><span>FORA</span></div></div><span class="analyze-link">Analisar jogo →</span></article>`}
function bindGameCards(){$$('.game-card').forEach(c=>c.addEventListener('click',()=>{$('#homeTeam').value=c.dataset.home;$('#awayTeam').value=c.dataset.away;showView('analyzer')}))}
async function loadFeatured(){const day=$('#dashboardDate').value;$('#featuredGames').innerHTML='<div class="skeleton">A carregar…</div>';try{const rows=await api('/api/fixtures?day='+day);$('#featuredGames').innerHTML=rows.slice(0,6).map(gameCard).join('')||'<div class="skeleton">Sem jogos.</div>';bindGameCards()}catch(e){$('#featuredGames').innerHTML=`<div class="skeleton">${esc(e.message)}</div>`}}
async function loadAllGames(){const day=$('#gamesDate').value;$('#allGames').innerHTML='<div class="skeleton">A carregar…</div>';try{const rows=await api('/api/fixtures?day='+day);$('#allGames').innerHTML=rows.map(g=>{const t=new Date(g.kickoff).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'});return `<div class="fixture-row"><b>${t}</b><small>${esc(g.league)}</small><div><b>${esc(g.home)}</b> <span class="muted">vs</span> <b>${esc(g.away)}</b></div><button class="ghost fixture-analyze" data-home="${esc(g.home)}" data-away="${esc(g.away)}">Analisar</button></div>`}).join('')||'<div class="skeleton">Sem jogos.</div>';$$('.fixture-analyze').forEach(b=>b.addEventListener('click',()=>{$('#homeTeam').value=b.dataset.home;$('#awayTeam').value=b.dataset.away;showView('analyzer')}))}catch(e){$('#allGames').innerHTML=`<div class="skeleton">${esc(e.message)}</div>`}}
function snapshot(s){return `<article class="snapshot"><h4>${esc(s.name)}</h4><div class="statline"><span>Jogos</span><b>${s.played}</b></div><div class="statline"><span>PPG</span><b>${num(s.ppg)}</b></div><div class="statline"><span>Golos / jogo</span><b>${num(s.goals_for)}</b></div><div class="statline"><span>xG / jogo</span><b>${num(s.xg_for)}</b></div><div class="statline"><span>xGA / jogo</span><b>${num(s.xg_against)}</b></div><div class="statline"><span>Remates enquadrados</span><b>${num(s.shots_on_target,1)}</b></div><div class="statline"><span>Cantos</span><b>${num(s.corners,1)}</b></div><div class="statline"><span>Lesões / susp.</span><b>${s.injuries} / ${s.suspensions}</b></div><div class="statline"><span>Descanso</span><b>${s.rest_days==null?'—':num(s.rest_days,0)+' d'}</b></div><div class="statline"><span>Elo/força</span><b>${num(s.elo,0)}</b></div></article>`}
function marketTable(markets){return `<table class="market-table"><thead><tr><th>Mercado</th><th>Modelo</th><th>Odd justa</th><th>Odd mercado</th><th>Edge</th><th>EV</th><th>Stake</th></tr></thead><tbody>${markets.map(m=>`<tr><td><b>${esc(m.market)}</b><small class="market-label">${esc(m.label)}</small></td><td>${pct(m.probability)}</td><td>${num(m.fair_odds)}</td><td>${num(m.market_odds)}</td><td class="${m.edge>0?'positive':m.edge<0?'negative':''}">${m.edge==null?'—':pct(m.edge)}</td><td class="${m.ev>0?'positive':m.ev<0?'negative':''}">${m.ev==null?'—':pct(m.ev)}</td><td>${euro(m.stake)}</td></tr>`).join('')}</tbody></table>`}
function componentBars(c){const mx=Math.max(...c.map(x=>x.home_goals+x.away_goals),1);return `<div class="component-list">${c.map(x=>`<div class="component-row"><div><b>${esc(x.name)}</b><small>peso ${(x.weight*100).toFixed(0)}%</small></div><div class="bar"><i style="width:${Math.min(100,(x.home_goals+x.away_goals)/mx*100)}%"></i></div><span>${num(x.home_goals)}–${num(x.away_goals)}</span></div>`).join('')}</div>`}
function renderAnalysis(d){lastAnalysis=d;const p=d.prediction,best=d.best_value;$('#analysisEmpty').classList.add('hidden');$('#analysisResult').classList.remove('hidden');$('#analysisResult').innerHTML=`<article class="score-hero"><div class="match-head"><p class="eyebrow">PROJEÇÃO DO ENSEMBLE</p><h2>${esc(d.home.name)} <span class="muted">vs</span> ${esc(d.away.name)}</h2><small class="muted">${esc(d.model.name)} · confiança ${pct(p.confidence)} · qualidade ${pct(p.data_quality)}</small></div><div class="prob-grid"><div class="prob"><small>CASA</small><strong>${pct(p.p_home)}</strong><span>odd justa ${num(1/p.p_home)}</span></div><div class="prob"><small>EMPATE</small><strong>${pct(p.p_draw)}</strong><span>odd justa ${num(1/p.p_draw)}</span></div><div class="prob"><small>FORA</small><strong>${pct(p.p_away)}</strong><span>odd justa ${num(1/p.p_away)}</span></div></div><div class="xg-line"><span>xG casa <b>${num(p.exp_home_goals)}</b></span><span>xG fora <b>${num(p.exp_away_goals)}</b></span><span>O2.5 <b>${pct(p.p_over25)}</b></span><span>BTTS <b>${pct(p.p_btts)}</b></span></div></article>
<article class="panel report"><p class="eyebrow">AI MATCH REPORT</p><h3>Leitura automática</h3><p>${esc(d.report)}</p></article>
${best?`<article class="panel ${best.ev>0?'':'warning'}"><p class="eyebrow">MELHOR VALOR DETETADO</p><h3>${esc(best.market)} · ${best.ev>0?'<span class="positive">EV '+pct(best.ev)+'</span>':'Sem value positivo'}</h3><p class="muted">Probabilidade ${pct(best.probability)} · odd justa ${num(best.fair_odds)} · stake Kelly ¼ ${euro(best.stake)}</p></article>`:''}
<article class="panel"><p class="eyebrow">MODELOS</p><h3>Contribuição do ensemble</h3>${componentBars(d.components)}</article>
<article class="panel"><p class="eyebrow">MERCADOS</p><h3>Preço justo vs mercado</h3><div class="table-wrap">${marketTable(d.markets)}</div></article>
<article class="panel"><p class="eyebrow">PLACARES</p><h3>Resultados exatos mais prováveis</h3><div class="scorechips">${d.scorelines.map(s=>`<span class="scorechip"><b>${s.home}-${s.away}</b> · ${pct(s.probability)}</span>`).join('')}</div></article><div class="snapshot-grid">${snapshot(d.home)}${snapshot(d.away)}</div>`;$('#valueTable').innerHTML='<div class="table-wrap">'+marketTable([...d.markets].sort((a,b)=>(b.ev??-99)-(a.ev??-99)))+'</div>'}
$('#analyzeForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('#formStatus').textContent='A calcular ensemble, contexto e value…';const val=id=>{const v=$(id).value;return v===''?null:Number(v)};const payload={home:$('#homeTeam').value.trim(),away:$('#awayTeam').value.trim(),kickoff_date:$('#kickoffDate').value||null,form_games:Number($('#formGames').value),home_advantage:Number($('#homeAdv').value),bankroll:Number($('#bankroll').value),home_injuries:Number($('#homeInj').value||0),away_injuries:Number($('#awayInj').value||0),home_suspensions:Number($('#homeSusp').value||0),away_suspensions:Number($('#awaySusp').value||0),home_rest_days:val('#homeRest'),away_rest_days:val('#awayRest'),home_lineup_strength:Number($('#homeLineup').value),away_lineup_strength:Number($('#awayLineup').value),odds_home:val('#oddsHome'),odds_draw:val('#oddsDraw'),odds_away:val('#oddsAway'),odds_over15:val('#oddsOver15'),odds_over25:val('#oddsOver'),odds_under25:val('#oddsUnder'),odds_over35:val('#oddsOver35'),odds_btts:val('#oddsBtts')};try{const d=await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderAnalysis(d);$('#formStatus').textContent='Análise concluída e guardada.'}catch(err){$('#formStatus').textContent=err.message}finally{btn.disabled=false}})
async function scanValue(){const day=$('#valueDate').value;$('#valueScanner').innerHTML='<div class="skeleton">A analisar jogos…</div>';try{const rows=await api('/api/value-finder?day='+day+'&bankroll='+Number($('#bankroll').value||1000));$('#valueScanner').innerHTML=rows.map((r,i)=>`<article class="value-card"><div><small>${esc(r.league)} · ${new Date(r.kickoff).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small><h3>${esc(r.home)} <span>vs</span> ${esc(r.away)}</h3><p>${esc(r.odds_source)}</p></div><div class="value-score"><small>${esc(r.best.market)}</small><b class="${r.best.ev>0?'positive':'negative'}">EV ${pct(r.best.ev)}</b><span>odd ${num(r.best.market_odds)} · stake ${euro(r.best.stake)}</span></div></article>`).join('')||'<div class="empty-inline">Sem oportunidades.</div>'}catch(e){$('#valueScanner').innerHTML=`<div class="empty-inline">${esc(e.message)}</div>`}}
async function runBacktest(){const n=Number($('#backtestSamples').value||500);$('#backtestResult').innerHTML='<div class="skeleton">A executar…</div>';try{const d=await api('/api/backtest/demo?samples='+n);$('#backtestResult').classList.remove('empty-state');$('#backtestResult').innerHTML=`<p class="eyebrow">RESULTADOS DEMO</p><div class="kpi-grid"><div><span>Apostas</span><b>${d.bets}</b></div><div><span>ROI</span><b class="${d.roi>=0?'positive':'negative'}">${pct(d.roi)}</b></div><div><span>Profit</span><b>${num(d.profit_units)}u</b></div><div><span>Brier</span><b>${num(d.brier,3)}</b></div><div><span>CLV médio</span><b>${pct(d.avg_clv)}</b></div></div><p class="muted">${esc(d.note)}</p>`}catch(e){$('#backtestResult').innerHTML=`<p>${esc(e.message)}</p>`}}
async function loadHistory(){try{const rows=await api('/api/history');$('#historyList').innerHTML=rows.map(r=>`<div class="fixture-row history-row"><b>${new Date(r.created_at).toLocaleDateString('pt-PT')}</b><small>${new Date(r.created_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small><div><b>${esc(r.home)}</b> <span class="muted">vs</span> <b>${esc(r.away)}</b></div><span class="muted">${pct(r.data.prediction?.confidence)}</span></div>`).join('')||'<div class="empty-inline">Ainda sem análises.</div>'}catch(e){$('#historyList').innerHTML=`<div class="empty-inline">${esc(e.message)}</div>`}}
function updateSession(){if(userEmail){$('#sessionTitle').textContent=userEmail;$('#sessionText').textContent='Sessão ativa. As novas análises ficam associadas a esta conta.';$('#logoutBtn').classList.remove('hidden')}else{$('#sessionTitle').textContent='Modo visitante';$('#sessionText').textContent='Podes analisar jogos sem conta. Faz login para separar o teu histórico.';$('#logoutBtn').classList.add('hidden')}}
async function auth(mode){const email=$('#authEmail').value.trim(),password=$('#authPassword').value;$('#authStatus').textContent='A processar…';try{const d=await api('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});token=d.token;userEmail=d.email;sessionStorage.setItem('fe_token',token);sessionStorage.setItem('fe_email',userEmail);$('#authStatus').textContent=mode==='login'?'Sessão iniciada.':'Conta criada.';updateSession()}catch(e){$('#authStatus').textContent=e.message}}
$('#loginBtn').addEventListener('click',()=>auth('login'));$('#registerBtn').addEventListener('click',()=>auth('register'));$('#logoutBtn').addEventListener('click',()=>{token='';userEmail='';sessionStorage.removeItem('fe_token');sessionStorage.removeItem('fe_email');updateSession()});
$('#loadGamesBtn').addEventListener('click',loadAllGames);$('#dashboardDate').addEventListener('change',loadFeatured);$('#refreshBtn').addEventListener('click',()=>{health();loadFeatured()});$('#scanValueBtn').addEventListener('click',scanValue);$('#runBacktestBtn').addEventListener('click',runBacktest);$('#loadHistoryBtn').addEventListener('click',loadHistory);
['dashboardDate','gamesDate','kickoffDate','valueDate'].forEach(id=>$('#'+id).value=todayISO());updateSession();health();loadFeatured();
